### ISSUE TITLE
Date cell values returning NaN

### ISSUE THREAD

**Issue by KenWade** [appdevdesigns/appdev-opsportal#135] opened 2016-11-06 05:09 UTC
Returning to the live application after development work shows all the dates that had been entered earlier as NaN/Nan/Nan

![image](https://cloud.githubusercontent.com/assets/14247188/20035506/94500f02-a419-11e6-8cef-51385d099e2e.png)

**Comment by KenWade** [comment] 2016-11-06 06:19
Also, in the AppDev developer, looking at an Object the dates in the table look OK:
![image](https://cloud.githubusercontent.com/assets/14247188/20035745/25ba2910-a423-11e6-9289-5163f0414904.png)

But, immediately switching over to Interface the dates are NaN/NaN/Nan:
![image](https://cloud.githubusercontent.com/assets/14247188/20035748/62137b96-a423-11e6-8426-fbe4d24f9a4c.png)

**Comment by wongpratan** [comment] 2016-11-17 02:35
I could not reproduce it. I think It should be fixed on
https://github.com/appdevdesigns/app_builder/commit/4cd6b1b1de31be15e7074cb31c1f68c460cc1f6e

If I will found this issue, then I will reopen it again.

**Closed by wongpratan** 2016-11-17 02:35 UTC
Labels: bug, ready
